global:
  nodes: 
    - aistorecpu1004.nsv.sjc11.nvmetal.net
    - aistorecpu1005.nsv.sjc11.nvmetal.net
    - aistorecpu1006.nsv.sjc11.nvmetal.net
  job_namespace: ais-jobs
  namespace: ais
  cluster: ais

ais-create-pv:
  mpath_size: 5.8Ti
  mpaths:
    - /ais/nvme0n1
    - /ais/nvme1n1
    - /ais/nvme3n1