---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ais-nvidia-com-v1beta1-aistore
  failurePolicy: Fail
  name: vaistore.kb.io
  rules:
  - apiGroups:
    - ais.nvidia.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - aistores
  sideEffects: None
