apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "ais.fullname" . }}-ne-proxy
  labels:
    app: {{ template "ais.name" . }}
    chart: {{ template "ais.chart" . }}
    component: "{{ .Values.ne_proxy.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      release: {{ .Release.Name }}
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "ais.name" . }}
        component: "{{ .Values.ne_proxy.name }}"
        release: {{ .Release.Name }}
        function: "gateway"
    spec:
      initContainers:
        - name: populate-env
          image: {{ .Values.aiscluster.image.kubectl.repository }}:{{ .Values.aiscluster.image.kubectl.tag }}
          imagePullPolicy: {{ .Values.aiscluster.image.pullPolicy }}
          env:
            - name: MY_NODE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name : ROLE
              value : "proxy"
          command:
            - "/bin/bash"
          args: [ "-c", "/bin/bash /var/ais_config/set_uuid_env.sh" ]
          volumeMounts:
            - name: config-mount
              mountPath: "/var/ais_config"
            - name: env-mount
              mountPath: "/var/ais_env"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.aiscluster.image.aisnode.repository }}:{{ .Values.aiscluster.image.aisnode.tag }}"
          imagePullPolicy: {{ .Values.aiscluster.image.pullPolicy }}
          securityContext:
            capabilities:
              add:
                {{ range .Values.aiscluster.k8s.container_capabilities }}
                - {{ . }}
                {{ end }}
          env:
            - name : CONFFILE
              value : "/var/ais_config/ais.json"
            - name: STATSDCONF
              value: "/var/statsd_config/statsd.json"
            - name : ROLE
              value : "proxy"
            - name: AIS_HOSTIP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: CLUSTERIP_PROXY_SERVICE_HOSTNAME
              value: {{ template "ais.fullname" . }}-proxy
            - name: CLUSTERIP_PROXY_SERVICE_PORT
              value: "{{ .Values.proxy.service.port }}"
          ports:
            - name: http
              containerPort: {{ .Values.ne_proxy.service.port }}
              protocol: TCP
          volumeMounts:
            - name: config-mount
              mountPath: "/var/ais_config"
            - name: env-mount
              mountPath: "/var/ais_env"
            - name: state-mount
              mountPath: "/etc/ais"
            - name: statsd-config
              mountPath: "/var/statsd_config"
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/bash", "-c", "/usr/bin/pkill -SIGINT aisnode" ]
          livenessProbe:
            httpGet:
              path: /v1/health
              port: {{ .Values.ne_proxy.service.port }}
            initialDelaySeconds: 90
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /v1/health
              port: {{ .Values.ne_proxy.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          resources:
{{ toYaml .Values.ne_proxy.resources | indent 12 }}
      securityContext:
        sysctls:
        - name: net.core.somaxconn
          value: {{ .Values.aiscluster.k8s.sysctls.somaxconn | quote }}
        - name: net.ipv4.ip_local_port_range
          value: "10240 65535"
      serviceAccount: {{ template "ais.name" . }}-sa
      nodeSelector:
         {{ .Values.ne_proxy.nodeSelector.key }}: {{ template "ais.fullname" . }}-nonelectable
      volumes:
        - name: config-mount
          configMap:
            name:  {{ template "ais.name" . }}-neproxy
        - name: env-mount
          hostPath:
            path: "{{ .Values.aiscluster.hostpathPrefix }}/{{ .Release.Name }}/ne_proxy_env"
        - name: state-mount
          hostPath:
            path: "{{ .Values.aiscluster.hostpathPrefix }}/{{ .Release.Name }}/ne_proxy"
        - name: statsd-config
          configMap:
            name: {{ template "ais.name" . }}-statsd
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      imagePullSecrets:
        {{- range .Values.aiscluster.image.pullSecretNames }}
        - name: {{ . }}
        {{- end }}