apiVersion: v1
kind: Service
metadata:
  name: {{ template "ais.fullname" . }}-target
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: {{ template "ais.name" . }}
    chart: {{ template "ais.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  # type: {{ .Values.target.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.target.service.port }}
      targetPort: {{ .Values.target.service.port }}
      protocol: TCP
      name: http
  selector:
      app: "{{ template "ais.name" . }}"
      release: "{{ .Release.Name }}"
