dependencies:
  #
  # Graphite server.
  #
  # Requires that we have already run 'helm repo add kiwigrid https://kiwigrid.github.io',
  # and also requires a 'helm dependency update' to pull in dependencies.
  #
  # - name: graphite
  #   version: ">=0.3.4"
  #   repository: https://kiwigrid.github.io
  #   tags:
  #    - builtin_monitoring

  #
  # The graphite dependency has been copied locally. We need to change some defaults in the config map
  # for graphite, but the quite large source there is not parametrized via values.yaml.
  # If you edit the configmap after graphite install we'd achieve the same result, but
  # we want to automate everything. We could copy the entire configmap into the parent
  # chart values.yaml to over-ride the few lines we need to, but it is nearly 1000 lines.
  # So instead we copy graphite into our charts directory and modify the config map there.
  # Chances are we'll need more extensive tweaking the the graphite config, anyway.

  #
  # Grafana server.
  #
  # Install from the standard repo (present if helm init has been run; if absent
  # 'helm init --client-only' assuming Tiller is already installed on k8s (as
  # kubespray does for us) or simply 'helm repo add stable https://kubernetes-charts.storage.googleapis.com'
  #
  - name: grafana
    version: ">=2.2.1"
    repository: https://kubernetes-charts.storage.googleapis.com/
    tags:
      - builtin_monitoring

  #
  # Prometheus
  #
  - name: prometheus
    version: ">=8.9.0"
    repository: https://kubernetes-charts.storage.googleapis.com
    tags:
      - builtin_monitoring
      - prometheus