---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    podMonitorSelector: prometheus
  name: aistore-proxy-podmonitor
spec:
  podMetricsEndpoints:
  - interval: 30s
    port: http
    path: /metrics
  namespaceSelector:
    matchNames:
    - ais
  selector:
    matchLabels:
      app: "aistore"
      component: "proxy"
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    podMonitorSelector: prometheus
  name: aistore-target-podmonitor
spec:
  podMetricsEndpoints:
  - interval: 30s
    port: http
    path: /metrics
  namespaceSelector:
    matchNames:
    - ais
  selector:
    matchLabels:
      app: "aistore"
      component: "target"
