---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aisauth-secrets.adminSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aisauth-secrets.labels" . | nindent 4 }}
type: Opaque
stringData:
  SU-NAME: {{ .Values.adminUsername | default "admin" | quote }}
  SU-PASS: {{ .Values.adminPassword | quote }}
{{- with .Values.hmacKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aisauth-secrets.hmacSecretName" $ }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aisauth-secrets.labels" $ | nindent 4 }}
type: Opaque
stringData:
  SIGNING-KEY: {{ . | quote }}
{{- end }}
{{- with .Values.rsaPassphrase }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aisauth-secrets.rsaPassphraseSecretName" $ }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aisauth-secrets.labels" $ | nindent 4 }}
type: Opaque
stringData:
  RSA-PASSPHRASE: {{ . | quote }}
{{- end }}
