---
# Creates a K8s Secret with the JWT Signing Key. Same secret can be used by AIStore Pods
apiVersion: v1
kind: Secret
metadata:
  name: jwt-signing-key
  namespace: ais
type: Opaque
data:
  SIGNING-KEY: YUJpdExvbmdTZWNyZXRLZXk= # base64 encoded value of "aBitLongSecretKey", `echo -n "aBitLongSecretKey" | base64`
---
# Deployment of AuthN Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authn-deployment
  namespace: ais
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authn
  template:
    metadata:
      labels:
        app: authn
    spec:
      containers:
      - name: authn
        image: aistorage/authn:latest
        ports:
        - containerPort: 52001
        env:
        # Environment variables for the AuthN Server, take precedence over config file values
        # Superuser (admin) name for AuthN
        - name: AIS_AUTHN_SU_NAME
          value: "admin"
        # Superuser (admin) password for AuthN  
        - name: AIS_AUTHN_SU_PASS
          value: "admin"
        # Secret key used to sign tokens
        - name: AIS_AUTHN_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-signing-key
              key: SIGNING-KEY
        # Port on which AuthN listens to requests
        - name: AIS_AUTHN_PORT
          value: "52001"
      # Uncomment the following block to enable HTTPS for AuthN server
      #   # Enable HTTPS for AuthN server. If true, requires AIS_SERVER_CRT and AIS_SERVER_KEY to be set
      #   - name: AIS_AUTHN_USE_HTTPS
      #     value: "true"
      #   # Path to the certificate file for HTTPS
      #   - name: AIS_SERVER_CRT
      #     value: "/var/certs/tls.crt"
      #   # Path to the key file for HTTPS
      #   - name: AIS_SERVER_KEY
      #     value: "/var/certs/tls.key"
      #   - name: AIS_AUTHN_USE_HTTPS
      #     value: "true"
      #   volumeMounts:
      #   - mountPath: /var/certs
      #     name: tls-certs
      #     readOnly: true
      # volumes:
      # - name: tls-certs
      #   secret:
      #     secretName: tls-certs
      #     defaultMode: 420
---
# Service for the AuthN Server to be accessed by CLI, SDKs, etc.
apiVersion: v1
kind: Service
metadata:
  name: ais-authn-nodeport
  namespace: ais
spec:
  selector:
    app: authn
  ports:
    - protocol: TCP
      port: 52001
      targetPort: 52001
      nodePort: 30001
  type: NodePort
---
# Service for the AuthN Server to be accessed by AIS-Operator
apiVersion: v1
kind: Service
metadata:
  name: ais-authn
  namespace: ais
spec:
  clusterIP: None
  selector:
    app: authn
  ports:
    - protocol: TCP
      port: 52001
      targetPort: 52001