nodeAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
      - matchExpressions:
        - key: monitoring
          operator: In
          values:
            - "true"

storageClass: local-path