replicaCount: 1

image:
  repository: quay.io/nvidia/aisloader
  tag: stable
  pullPolicy: IfNotPresent
  pullSecret: ais-pull-secret

#
# The release name and namespace for the AIS instance we'll target - must be supplied
# The release name will also be used as nodeSelector for the DaemonSet
#
ais_release: ""
ais_namespace: ""

#
# Arguments for the controller pod; see README.md
#
controller:
  #
  # When runid changes (and is not 'nil') then the controller pod will kick off a new
  # benchmark run on the requested number of aisloader nodes, all running config
  # as per config.
  #
  runid: nil  
  #
  # Number of aisloader nodes to run on
  #
  nodecount: 1
  #
  # Existing PVC to use for storing results; leave empty for EmptyDir
  #
  results_pvc:

  #
  # Sleep time in seconds for daemonset pod after aisloader completes - set nonzero or
  # to infinity for debug.
  #
  postrun_snooze: 60

#
# Arguments with which to run aisloader in the daemonset pods.
# See https://github.com/NVIDIA/aistore/tree/master/bench/aisloader - we'll include one
# line descriptions below.
#
# In each case we first look for an argument indexed by node name, and fall back to the
# default.
#
# 'ip' default is not listed below, it defaults to "{{ .Values.ais_release}}-ais-proxy }}"
#
config:
  bucket:           # AIStore bucket to use in run; %s, if present, is replaced by node name; created is absent
    default: "stressbkt"
    specific: []
  duration:         # Time to run, 0 means unbounded
    default: "30m"
    # Example of how to specify per-host values
    # specific:
    #  - node: "cpu01"
    #    value: "29m"
  pctput:           # Percentage of PUTs in workload (generated objs); GETs = 100 - this
    default: "0"
    specific: []
  cleanup:          # Delete test bucket on completion
    default: "false"
    specific: []
  numworkers:       # Num of parallel workers in aisloader daemonset instance
    default: "50"
    specific: []
  uniquegets:       # false => choose obj to read randomly; true => random but assure full bkt traversal ala DL epoch
    default: "true"
    specific: []
  readlen:          # how much of object to read on GET; 0 => all
    default: "0"
    specific: []
  readoff:          # offset to start read at
    default: "0"
    specific: []
  minsize:          # for PUTs, minimum size of generated object
    default: "1G"
    specific: []
  maxsize:          # for PUTs, maximum size of generated object
    default: "1G" 
    specific: []
  maxputs:          # maximum number of PUTs to perform (use with unbounded duration to limit data generation)
    default: "0"
    specific: []
  putshards:        # generate obj in this many subdirectories (prefixes) named as %06x/<random-name>; for fs with big dir issues
    default: "0"
    specific: []
  seed:             # random seed; fromhostip => last component of host IP, random => $RANDOM), 0 => time in ns
    default: "fromhostip"
    specific: []
  ip:               # IP/hostname of AIS proxy service - usually derived from AIS instance info
    # no default - see above
    specific: []
  port:             # Port number for AIS proxy service
    default: "51080"
    specific: []
  readertype:       # Reader type; sg, file, inmem, read
    default: "sg"
    specific: []
  statsinterval:    # Graphite stats reporting interval
    default: "60"
    specific: []

aisloaderEnv:
#  - name: FOO
#    value: bar 

resources: {}

sysctls:
  # set to zero if k8s not allowing unsafe sysctl, but needed if working on many
  # small objexts
  somaxconn: 100000

#
# Over-rides for redis dependency
#
redis:
  usePassword: false
  master:
    persistence:
      enabled: false
  slave:
    persistence:
      enabled: false

tolerations: []

affinity: {}
