# Run this and restart the cluster pods to update access to aws 
# Copies the provided aws config and credentials files in roles/aws_config/files to the controller host
# and recreates the kubernetes secret 

- hosts: controller
  vars_files:
    - "vars/aws_config.yml"

  gather_facts: false
  roles:
    - aws_config
