init_image: aistorage/ais-init:v3.23
node_image: aistorage/aisnode:v3.23

# Cloud
gcp_secret_name: ""
aws_secret_name: ""

# Extra sysctl config to apply to pods -- change apply_sysctls to true to apply
apply_sysctls: false
tcp_tw_reuse: 1
tcp_max_tw_buckets: 1440000
ip_local_port_range: 2048 65535
somaxconn: 65535

# cluster domain name for DNS
cluster_domain: "cluster.local"

# logs directory
logs_dir: "/var/log/ais"

# unequal num of proxy and target
# Note: 0 < proxy_size, target_size <= cluster_size
# proxy_size: 1
# target_size: 3

# if true, the AIS Daemon pods for target are created in the host's network namespace (used for multihoming)
host_network: false