ais_host_sysctl_override:
  - name: net.ipv4.tcp_mem
    value: 9087424 12116566 18174849
    state: present
    comment: In pages, usually based on available memory. Depending on other settings, this may need increased to help overall TCP memory usage. See https://access.redhat.com/solutions/6964027 for RHEL defaults. 
  