# This file contains the default values for the sysctl settings.
# These are only suggestions and MUST be tuned per your hosts, as many depend on network speed, memory, etc.  
# See environments/README.md for details on how to override these values per environment.
# Note that any overridden section must override the entire section as ansible does not merge by default. 

# Applied in lexicographic order, tweak if needed override existing conf on your system
required_sysctl_file: /etc/sysctl.d/100-ais-required.conf
network_sysctl_file: /etc/sysctl.d/100-ais-network.conf
vm_sysctl_file: /etc/sysctl.d/100-ais-vm.conf

#
# Items to add/tweak in /etc/sysctl.conf.d/ 
# The 'default' and 'comment' fields are just for reference.
#
# Ensure your system has sufficient memory to handle the increased limits,
# especially for tcp_max_tw_buckets and somaxconn.
#
# See https://www.ibm.com/docs/en/linux-on-systems?topic=tuning-tcpip-ipv4-settings
# for guidance on specific values.
#
# The default limits here are exceeded very readily under even modest load.
#
# Tags: sysctlrequired
#
ais_host_sysctl_required:
  - name: net.core.somaxconn
    value: 65535
    default: 128
    state: present
    comment: Maximum number of connection requests that can be queued to a given listening socket. Needs to absorb burst of connection requests. AIS clients will usually keep connections open to proxy and targets, so we do not expect ongoing high new connection rate.
  - name: net.ipv4.tcp_tw_reuse
    value: 1
    default: 0
    state: present
    comment: If sockets hang around in timewait state for long then (since we're PUTting and GETting lots of objects) we very soon find that we exhaust local port range. So we stretch the available range of local ports (ip_local_port_range), increase the max number of timewait buckets held by the system simultaneously (tcp_max_tw_buckets), and reuse sockets in timewait state as soon as it is "safe from a protocol point of view" (whatever that means, tcp_tw_reuse).
  - name: net.ipv4.ip_local_port_range
    value:   2048 65535 
    default: 32768 60999 
    state: present
    comment: See comment for tw_reuse
  - name: net.ipv4.tcp_max_tw_buckets
    value:   1440000
    default:  262144
    state: present
    comment: Maximal number of timewait sockets held by system simultaneously. If this number is exceeded time-wait socket is immediately destroyed and warning is printed. This limit exists only to prevent simple DoS attacks, you must not lower the limit artificially, but rather increase it (probably, after increasing installed memory), if network conditions require more than default value. See comment for tw_reuse.


#
# If you have fast networking you're going to have to tune these for good results, but we can't
# anticipate all environments so these are not applied unless requested. If you already have
# your own tuning stick with that for starters; if you have little tuning and big network
# pipes then use this as a starting point. These values worked well on hosts with 50 and
# 100 GigE Mellanox CX-5 cards.
#
# See https://blog.cloudflare.com/optimizing-tcp-for-high-throughput-and-low-latency/
# for details on optimizing for higher throughput
#
# Tags: sysctlnet
#
ais_host_sysctl_net:
  - name: net.ipv4.ip_forward
    value: 1
    default: 0
    state: present
    comment: Kubespray requirement
  - name: net.core.optmem_max
    value: 25165824
    default: 20480
    state: present
    comment: Max ancillary buffer size. Some say must tune up, some say no difference.
  - name: net.core.rmem_max
    value: 134217728
    default: 212992 - 208 KB
    comment: 128MB, based on a Bandwidth Delay Product of ~64MB and tcp_adv_win_scale of 1. 
  - name: net.core.wmem_max
    value: 134217728
    default: 212992 - 208 KB
    comment: 128MB, based on a Bandwidth Delay Product of ~64MB and tcp_adv_win_scale of 1. 
  - name: net.core.netdev_max_backlog
    value: 250000
    default: 1000
    state: present
    comment: Maximum number of packets queued on input side if kernel is unable to process packet fast enough to keep up with receive rate. Value per Mellanox tuning guide. See https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/monitoring_and_managing_system_status_and_performance/tuning-the-network-performance_monitoring-and-managing-system-status-and-performance#tuning-the-network-device-backlog-queue-to-avoid-packet-drops_tuning-network-adapter-settings 
  - name: net.ipv4.tcp_mem
    value: 9087424 12116566 18174849
    state: present
    comment: In pages, usually based on available memory. Depending on other settings, this may need increased to help overall TCP memory usage. See https://access.redhat.com/solutions/6964027 for RHEL defaults. 
  - name: net.ipv4.tcp_wmem
    value:   4096    16384    134217728
    default: 4096    16384      4194304 (max is calculated)
    state: present
    comment: Min guaranteed under memory pressure, default, and maximum TCP send socket size. Applies only to automatically-sized buffers (as used in AIS) - apps that set SO_SNDBUF get what they request. Allow automatic sizing up to 128M.
  - name: net.ipv4.tcp_rmem
    value:   4096    262144    134217728
    default: 4096     87380      6291456 (max is calculated)
    state: present
    comment: Min guaranteed under memory pressure, default, and maximum TCP receive socket size. Applies only to automatically-sized buffers (as used in AIS) - apps that set SO_RCVBUF get what they request. Allow automatic sizing up to 128M.
  - name: net.ipv4.tcp_adv_win_scale
    value: 1
    default: 2
    state: present
    comment: Advised by Melanox docs (https://community.mellanox.com/s/article/linux-sysctl-tuning); share socket buffer equally between app and kernel, default is app gets 1/4.
  - name: net.ipv4.tcp_mtu_probing
    value: 2
    default: 0
    state: present
    comment: We control the MTU within the cluster nodes and k8s pods, so we can always use an initial MSS of tcp_base_mss.
  - name: net.ipv4.tcp_slow_start_after_idle
    value: 0
    default: 1
    state: present
    comment: No RFC2861 decay of the congestion window when all on same fast LAN
  - name: net.ipv4.tcp_max_syn_backlog
    value: 100000
    state: present
    default: 2048
    comment: Tolerate more half-open connections
  - name: net.ipv4.tcp_rfc1337
    value: 1
    state: present
    default: 0
    comment: Defend against time-wait assassination hazards

#
# Tags: sysctlvm
#
ais_host_sysctl_vm:
  - name: vm.swappiness
    value: 10
    state: present
    default: 60
    comment: Lowering this makes the kernel less inclined to push pages to swap unless we are close to using all memory.
  - name: vm.min_free_kbytes
    value: 7922082
    state: present
    default: Variable, but too low for our purposes. On E5 nodes, 159214. 
    comment: Ideally set to around 0.5-1% of system memory, and always < 5%. See https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/6/html/performance_tuning_guide/s-memory-tunables.
  - name: vm.vfs_cache_pressure
    value: 50
    state: present
    default: 100
    comment: Values lower than 100 are suitable for file servers in which we want to keep directory and inode objects in memory. 