---
- name: Copy cluster yaml with elevated privileges
  become: true
  template:
    src: "ais.yaml.j2"
    dest: "/tmp/{{ cluster }}.yaml"
    mode: 0777
    lstrip_blocks: true
  vars:
    cluster: "{{ cluster }}"
    cluster_size: "{{ groups[cluster] | length }}"

- name: Create namespace if not exists
  shell: "kubectl create ns {{ cluster }} || true"
  register: namespaceout
  changed_when: "'created' in namespaceout.stdout"

- name: Deploy clusters
  command: "kubectl apply -f /tmp/{{ cluster }}.yaml"
  register: createout
  changed_when: "'configured' in createout.stdout or 'created' in createout.stdout"
