---
- name: Delete clusters pods
  command: "kubectl delete aistores.ais.nvidia.com -n ais ais || true"
  register: deleteout
  changed_when: "'deleted' in deleteout.stdout or 'deleted' in deleteout.stdout"
  ignore_errors: true

- name: Copy cluster yaml
  template:
    src: "ais.yaml.j2"
    dest: "/tmp/{{ cluster }}.yaml"
    mode: 0777
    lstrip_blocks: true
  vars:
    cluster: "{{ cluster }}"
    cluster_size: "{{ groups[cluster] | length }}"

- name: Create namespace if not exists
  shell: "kubectl create ns {{ cluster }} || true"
  register: namespaceout
  changed_when: "'created' in namespaceout.stdout"

- name: Deploy clusters
  command: "kubectl apply -f /tmp/{{ cluster }}.yaml"
  register: createout
  changed_when: "'configured' in createout.stdout or 'created' in createout.stdout"
