# Default environment deploys the entire stack and defines local storage options

# Update with the user and group to run monitoring
securityContext:
  runAsGroup: 1003
  runAsNonRoot: true
  runAsUser: 1005
  fsGroup: 1005

affinity:
  enabled: true
  nodeMatchKey: aistore.nvidia.com/role_monitoring

grafana:
  enabled: true
  datasources:
    loki: 
      url: http://loki-gateway.monitoring.svc.cluster.local/
  persistence:
    storageClassName: local-path
    size: 20Gi

loki:
  enabled: true
  storageClass: local-path
  compactor:
    retention_enabled: true
  limitsConfig:
    retention_period: 336h

alertmanager:
  enabled: true
  slack:
    # Update to allow slack alerts
    webhook: ""
    channel: ""

promtail: 
  clientUrl: "http://loki-gateway/loki/api/v1/push"
