apiVersion: v1
entries:
  ais-operator:
  - apiVersion: v2
    appVersion: 1.6.1
    created: "2024-12-09T15:10:50.676628-06:00"
    description: A Helm chart for Kubernetes
    digest: d2d4d282bb5a73604801f2db6a0fdee5923972b762634bf2419198dc422087ff
    name: ais-operator
    type: application
    urls:
    - https://NVIDIA.github.io/ais-k8s/charts/ais-operator-1.6.1.tgz
    version: 1.6.1
  - apiVersion: v2
    appVersion: 1.6.0
    created: "2024-12-09T15:10:50.675795-06:00"
    description: A Helm chart for Kubernetes
    digest: bcb0d4a13f777b1ad6c26410c7e99558229e97dab6335432ec8f9da9c31f6bb6
    name: ais-operator
    type: application
    urls:
    - https://NVIDIA.github.io/ais-k8s/charts/ais-operator-1.6.0.tgz
    version: 1.6.0
  - apiVersion: v2
    appVersion: 1.5.0
    created: "2024-12-09T15:10:50.673401-06:00"
    description: A Helm chart for Kubernetes
    digest: 5e916efc97bad56df72aa35350b8bb6a90304bf060df05811572e37e731c7833
    name: ais-operator
    type: application
    urls:
    - https://NVIDIA.github.io/ais-k8s/charts/ais-operator-1.5.0.tgz
    version: 1.5.0
  - apiVersion: v2
    appVersion: 1.4.1
    created: "2024-12-09T15:10:50.670472-06:00"
    description: A Helm chart for Kubernetes
    digest: 047ee513468d4a021faae41c1308234f688b903aa2f4be69c7a68c3478513415
    name: ais-operator
    type: application
    urls:
    - https://NVIDIA.github.io/ais-k8s/charts/ais-operator-1.4.1.tgz
    version: 1.4.1
generated: "2024-12-09T15:10:50.667356-06:00"
