apiVersion: v1
entries:
  ais-operator:
  - apiVersion: v2
    appVersion: 1.4.1
    created: "2024-10-17T21:14:44.290832-05:00"
    description: A Helm chart for Kubernetes
    digest: 047ee513468d4a021faae41c1308234f688b903aa2f4be69c7a68c3478513415
    name: ais-operator
    type: application
    urls:
    - https://NVIDIA.github.io/ais-k8s/charts/ais-operator-1.4.1.tgz
    version: 1.4.1
generated: "2024-10-17T21:14:44.289943-05:00"
