apiVersion: v1
entries:
  ais-operator:
  - apiVersion: v2
    appVersion: 2.1.2
    created: "2025-04-14T14:22:07.293288-05:00"
    description: A Helm chart for Kubernetes
    digest: 461362630c32d2e414c380eef3a923503205eaaa9f7d21439a6a3509779ee91f
    name: ais-operator
    type: application
    urls:
    - https://NVIDIA.github.io/ais-k8s/charts/ais-operator-2.1.2.tgz
    version: 2.1.2
  - apiVersion: v2
    appVersion: 2.1.1
    created: "2025-04-14T14:22:07.292364-05:00"
    description: A Helm chart for Kubernetes
    digest: 421d2d480de7e221f55432e6c379fc84b9e532b1c028665466692aec6bd86d05
    name: ais-operator
    type: application
    urls:
    - https://NVIDIA.github.io/ais-k8s/charts/ais-operator-2.1.1.tgz
    version: 2.1.1
  - apiVersion: v2
    appVersion: 2.1.0
    created: "2025-04-14T14:22:07.290161-05:00"
    description: A Helm chart for Kubernetes
    digest: e9dc47b0e6d2e34f3ef124f5caad562db448b3f5844a938fa81095b3fd8174aa
    name: ais-operator
    type: application
    urls:
    - https://NVIDIA.github.io/ais-k8s/charts/ais-operator-2.1.0.tgz
    version: 2.1.0
  - apiVersion: v2
    appVersion: 2.0.1
    created: "2025-04-14T14:22:07.287516-05:00"
    description: A Helm chart for Kubernetes
    digest: 7103a4c8e3e3d77cb172fef924f60623ddeecd16c63c9db6195585fbe031f6f8
    name: ais-operator
    type: application
    urls:
    - https://NVIDIA.github.io/ais-k8s/charts/ais-operator-2.0.1.tgz
    version: 2.0.1
  - apiVersion: v2
    appVersion: 2.0.0
    created: "2025-04-14T14:22:07.285418-05:00"
    description: A Helm chart for Kubernetes
    digest: bdd95e3c383d6786c40aa293c4b3126e9d5a169138cdc878bb9fee8a754f5406
    name: ais-operator
    type: application
    urls:
    - https://NVIDIA.github.io/ais-k8s/charts/ais-operator-2.0.0.tgz
    version: 2.0.0
  - apiVersion: v2
    appVersion: 1.7.0
    created: "2025-04-14T14:22:07.282849-05:00"
    description: A Helm chart for Kubernetes
    digest: 0790b3c362a15a000d007f5aed61fcf32aba581eb278c3966552471e017911bb
    name: ais-operator
    type: application
    urls:
    - https://NVIDIA.github.io/ais-k8s/charts/ais-operator-1.7.0.tgz
    version: 1.7.0
  - apiVersion: v2
    appVersion: 1.6.1
    created: "2025-04-14T14:22:07.278984-05:00"
    description: A Helm chart for Kubernetes
    digest: d2d4d282bb5a73604801f2db6a0fdee5923972b762634bf2419198dc422087ff
    name: ais-operator
    type: application
    urls:
    - https://NVIDIA.github.io/ais-k8s/charts/ais-operator-1.6.1.tgz
    version: 1.6.1
  - apiVersion: v2
    appVersion: 1.6.0
    created: "2025-04-14T14:22:07.275889-05:00"
    description: A Helm chart for Kubernetes
    digest: bcb0d4a13f777b1ad6c26410c7e99558229e97dab6335432ec8f9da9c31f6bb6
    name: ais-operator
    type: application
    urls:
    - https://NVIDIA.github.io/ais-k8s/charts/ais-operator-1.6.0.tgz
    version: 1.6.0
  - apiVersion: v2
    appVersion: 1.5.0
    created: "2025-04-14T14:22:07.273146-05:00"
    description: A Helm chart for Kubernetes
    digest: 5e916efc97bad56df72aa35350b8bb6a90304bf060df05811572e37e731c7833
    name: ais-operator
    type: application
    urls:
    - https://NVIDIA.github.io/ais-k8s/charts/ais-operator-1.5.0.tgz
    version: 1.5.0
  - apiVersion: v2
    appVersion: 1.4.1
    created: "2025-04-14T14:22:07.269613-05:00"
    description: A Helm chart for Kubernetes
    digest: 047ee513468d4a021faae41c1308234f688b903aa2f4be69c7a68c3478513415
    name: ais-operator
    type: application
    urls:
    - https://NVIDIA.github.io/ais-k8s/charts/ais-operator-1.4.1.tgz
    version: 1.4.1
generated: "2025-04-14T14:22:07.266462-05:00"
