apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-control
  labels:
spec:
  imagePullSecrets:
    - name: ais-pull-secret
  containers:
  - name: mycont
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    imagePullPolicy: IfNotPresent
    env:
      - name: REDISHOST
        value: "{{ .Release.Name }}-redis-master"
    volumeMounts:
      - name: aisloader-scripts
        mountPath: "/var/aisloader_scripts"
    command: [ "/bin/bash", "/var/aisloader_scripts/aisloader_control_logic.sh" ]
  volumes:
    - name: aisloader-scripts
      configMap:
        name: {{ template "chart.name" . }}-scripts