apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "chart.name" . }}-scripts
data:
  aisloader_client_config.sh: |-
{{ include "aisloader_client_config.sh" . | indent 4 }}
  aisloader_client_logic.sh: |-
{{ include "aisloader_client_logic.sh" . | indent 4 }}
  aisloader_control_config.sh: |-
{{ include "aisloader_control_config.sh" . | indent 4 }}
  aisloader_control_logic.sh: |-
{{ include "aisloader_control_logic.sh" . | indent 4 }}