#
# Apply node taints. Run for every host in the play, executes action on local host.
#

- name: Check whether storage node taint is applied
  local_action:
    module: shell
    _raw_params: kubectl describe node {{ inventory_hostname }} | grep --before=0 --after=10 '^Taints:' | grep '{{ cpu_node_taint }}'
  ignore_errors: True
  register: taintgrep

- name: Apply taint to node
  local_action:
    module: command
    _raw_params: kubectl taint nodes {{ inventory_hostname }} {{ cpu_node_taint }}
  when: taintgrep|failed