- name: Check k8s_namespace variable
  fail:
    msg: "`k8s_namespace` name must be provided!"
  when: k8s_namespace is undefined or k8s_namespace | length == 0

- name: Create namespace if it does not exist
  shell: "kubectl create ns {{ k8s_namespace }} || true"
  register: namespaceout
  changed_when: "'created' in namespaceout.stdout"