#
# Enable the multiqueue schedulers in Ubuntu 18.04 - requires reboot for effect.
#
---

- hosts: '{{ ais_hosts | default("ais") }}'
  gather_facts: false
  vars_prompt:
    - name: multiqueue_confirmation
      prompt: "Are you sure you want to run ais_enable_multiqueue on {{ ais_hosts }} cluster? Type 'yes' to confirm."
      default: "no"
      private: no
  become: true
  roles:
    - role: ais_enable_multiqueue
      when: multiqueue_confirmation | bool
