#
# Apply sysctl tweaks to the 'ais' host group
#
---
- hosts: '{{ ais_hosts | default("ais") }}'
  become: true
  gather_facts: false
  vars_files:
    - "vars/host_config_sysctl.yml"  # Base variables

  vars_prompt:
    - name: host_config_confirmation
      prompt: "Are you sure you want to run ais_host_config_sysctl with {{ env | default('default') }} settings on {{ ais_hosts }} cluster? Type 'yes' to confirm."
      default: "no"
      private: no

  tasks:
    - name: Include environment-specific sysctl overrides (if `env` is set)
      include_vars: "vars/environments/{{ env }}/host_config_sysctl.yml"
      when: env is defined

  roles:
    - role: ais_host_config_sysctl
      when: host_config_confirmation | bool