#
# Config specific to GPU hosts
#
---
- hosts: '{{ ais_hosts }}'
  vars_files:
    - "vars/host_config_packages.yml"

  gather_facts: true
  roles:
    - ais_gpuhost_config
    - ais_gpuhost_device_plugin



