#
# Apply our desired config to the 'ais' host group
#
# This config is intended to apply to *all* hosts; another playbook
# addresses specific needs for GPU hosts.
#
---
- hosts: '{{ ais_hosts | default("ais") }}'
  vars_files:
    - "vars/host_config.yml"
  vars_prompt:
    - name: host_config_confirmation
      prompt: "Are you sure you want to run ais_host_config_common on {{ ais_hosts }} cluster? Type 'yes' to confirm."
      default: "no"
      private: no
  become: true
  gather_facts: false
  roles:
    - role: ais_host_config_common
      when: host_config_confirmation | bool