# This role populates variables in the ais.yaml template, copies it to cluster, and applies it
- name: Create hostname map if additional hosts are defined
  set_fact:
    hostname_map: "{{ hostname_map | default({}) | combine({ primary_host_key: all_hosts }) }}"
  vars:
    primary_host_key: "{{ hostvars[host_entry]['ansible_host'] | default(host_entry) }}"
    all_hosts: "{{ hostvars[host_entry]['ansible_host'] | default(host_entry) }},{{ hostvars[host_entry]['additional_hosts'] }}"
  loop: "{{ groups[cluster] }}"
  loop_control:
    loop_var: host_entry
  when: additional_hosts is defined

- name: Load sysctl changes from template
  set_fact:
    sysctls: "{{ lookup('template', 'sysctls.json.j2') }}"
  when: apply_sysctls | bool

- name: Copy cluster yaml
  template:
    src: "ais.yaml.j2"
    dest: "/tmp/{{ cluster }}.yaml"
    mode: 0777
    lstrip_blocks: true
  vars:
    cluster: "{{ cluster }}"
    cluster_size: "{{ groups[cluster] | length }}"

- name: Deploy cluster
  command: "kubectl apply -f /tmp/{{ cluster }}.yaml"
  register: createout
  changed_when: "'configured' in createout.stdout or 'created' in createout.stdout"
