{{- if and .Values.aws_config .Values.aws_credentials .Values.cloud.awsSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cloud.awsSecretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  config: {{ .Values.aws_config | b64enc }}
  credentials: {{ .Values.aws_credentials | b64enc }}
{{- end }}