{{- if .Values.gcp_json }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cloud.gcpSecretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  gcp.json: {{ .Values.gcp_json | b64enc }}
{{- end }}