{{- if and .Values.oci_config .Values.oci_api_key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cloud.ociSecretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  config: {{ .Values.oci_config | b64enc }}
  {{- if and .Values.oci_cli_rc }}
  oci_cli_rc: {{ .Values.oci_cli_rc | b64enc }}
  {{- end }}
  oci_api_key: {{ .Values.oci_api_key | b64enc }}
{{- end }}