---
- name: Copy clean-up scripts
  copy:
    src: "clear-markers.sh"
    dest: "/tmp/"
    mode: 0777

- name: Run delete scripts
  shell: "MPATHS={{ ais_mpaths | join(' ') | quote }} /tmp/clear-markers.sh"
