apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: monitoring
data:
  config.alloy: |-
{{ tpl (.Files.Get (printf "environments/%s/config.alloy.gotmpl" .Values.environment)) . | indent 4 }}