# permissions for end users to edit aisconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aisconfig-editor-role
rules:
- apiGroups:
  - ais.nvidia.com
  resources:
  - aisconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ais.nvidia.com
  resources:
  - aisconfigs/status
  verbs:
  - get
