# permissions for end users to view aistores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aistore-viewer-role
rules:
- apiGroups:
  - ais.nvidia.com
  resources:
  - aistores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ais.nvidia.com
  resources:
  - aistores/status
  verbs:
  - get
