#
# Create a certificate using cert-manager for use of https
# based AIStore deployments
#
---
- name: Generate TLS certificates
  hosts: controller
  gather_facts: false
  vars_files:
    - vars/https_config.yml
  roles:
    - ais_https_cert

- name: Fetch CA certificate for client
  hosts: controller
  gather_facts: false
  vars_files:
    - vars/https_config.yml
  pre_tasks:
    - name: Check if cacert_file is defined
      set_fact:
        skip_play: "{{ cacert_file is not defined }}"
  tasks:
    - name: Fetch certificate if cacert_file is defined
      include_role:
        name: ais_fetch_cert
      when: not skip_play
