---
# Playbook for decommissioning the AIS cluster
# In decommission, all the configuration specific to AIStore is deleted from the nodes

- name: Decommission cluster from controller
  hosts: "controller"
  vars_prompt:
  - name: "decomm_confirmation"
    prompt: "Are you sure you would like to decommission cluster - {{ cluster }}? Type 'yes' to confirm."
    default: "no"
    private: no

  - name: "cleanup_data"
    prompt: "Would you like to cleanup all user data (buckets and objects) from disks? Type 'yes' to confirm."
    default: "no"
    private: no

  pre_tasks:
    - name: check confirmation
      fail:
        msg: "decommission cluster not confirmed/forced"
      when: decomm_confirmation != "yes"

    - name: check cluster name
      fail:
        msg: "cluster name not specified!"
      when: cluster is undefined

  gather_facts: false
  become: true
  roles:
    - role: ais_decommission_cluster
  vars:
    decommission_cluster: true

- name: Reset AIS configuration
  hosts: "{{ cluster }}"
  gather_facts: no
  become: true
  vars_files:
    - "vars/ais_mpaths.yml"
  vars_prompt:
    - name: "delete_conf"
      prompt: "Would you also like to delete all AIS config files from all nodes"
      default: "no"
      private: no

  roles:
    - role: ais_reset_config