---
# Playbook for switching the deployment protocol for AIS (HTTP ⇌ HTTPS)

- name: Delete all AIS pods from the cluster
  hosts: controller
  gather_facts: false
  become: true
  roles:
    - ais_delete_all_pods

- name: Reset AIS configuration
  hosts: "{{ cluster }}"
  gather_facts: false
  become: true
  roles:
    - ais_reset_config

- name: Redeploy AIS cluster
  hosts: controller
  gather_facts: false
  become: true
  roles:
    - ais_deploy_cluster
  vars_files:
    - "vars/ais_mpaths.yml"
    - "vars/https_config.yml"
    - "vars/multihome.yml"
  vars:
    redeploy: "true"
