---
- name: Undeploy AIStore AuthN Server
  hosts: controller
  become: yes
  gather_facts: no
  pre_tasks:
    - name: Validate if cluster is defined
      fail:
        msg: "Variable 'cluster' not found. Add the 'cluster' variable during execution. Use: ansible-playbook -i hosts.ini ais_undeploy_authn.yml -e cluster=ais"
      when: cluster is undefined
  tasks:
    - name: Delete AuthN Deployment
      command: kubectl delete deployment authn-deployment -n {{ cluster }}
      ignore_errors: yes

    - name: Delete JWT Signing Key Secret
      command: kubectl delete secret jwt-signing-key -n {{ cluster }}
      ignore_errors: yes

    - name: Delete AuthN NodePort Service
      command: kubectl delete service ais-authn-nodeport -n {{ cluster }}
      ignore_errors: yes

    - name: Delete AuthN ClusterIP Service
      command: kubectl delete service ais-authn -n {{ cluster }}
      ignore_errors: yes

