# Set variables based on the root context to be accessible within the range
{{- $cluster := .Values.cluster -}}
{{- $mpathInfo := .Values.mpathInfo -}}
{{- $storageClass := $mpathInfo.storageClass -}}
{{- $mpathSize := $mpathInfo.size -}}
{{- $paths := $mpathInfo.paths -}}
{{- $nodes := .Values.nodes -}}

{{- range $nodeIndex, $node := $nodes }}
  {{- range $mpathIndex, $mpath := $paths }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $node }}-pv-{{ $mpath | replace "/" "-" | trimPrefix "-" }}
  labels:
    type: local
    cluster: {{ $cluster }}
    mpath: pv-{{ $mpath | replace "/" "-" | trimPrefix "-" }}
spec:
  storageClassName: {{ $storageClass }}
  capacity:
    storage: {{ $mpathSize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ $mpath }}
  claimRef:
    name: {{ $cluster }}-{{ $mpath | replace "/" "-" | trimPrefix "-" }}-{{ $cluster }}-target-{{ $nodeIndex }}
    namespace: {{ $.Values.namespace }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ $node }}
---
  {{- end }}
{{- end }}
