- name: Copy PV scripts/templates
  copy:
    src: "{{ item }}"
    dest: "/tmp"
    mode: 0777
  loop:
    - "create-pvs.sh"
    - "pv.template.yaml"
    - "label-nodes.sh"

- name: Copy cluster yaml
  template:
    src: "ais.yaml.j2"
    dest: "/tmp/{{ cluster }}.yaml"
    mode: 0777
    lstrip_blocks: true
  vars:
    cluster: "{{ cluster }}"
    cluster_size: "{{ groups[cluster] | length }}"

- name: Create PVs
  shell: "MPATH_SIZE={{ ais_mpath_size }} MPATHS={{ ais_mpaths | join(' ') | quote }} NODES={{ groups[cluster] | join(' ') | quote }} /tmp/create-pvs.sh"
  register: createpvsout
  changed_when: "'configured' in createpvsout.stdout or 'created' in createpvsout.stdout"

- name: Create namespace if not exists
  shell: "kubectl create ns {{ cluster }} || true"
  register: namespaceout
  changed_when: "'created' in namespaceout.stdout"

- name: Label nodes
  shell: "CLUSTER={{ cluster }} NODES={{ groups[cluster] | join(' ') | quote }} /tmp/label-nodes.sh"
  register: labelout
  changed_when: "'labled' in labelout.stdout"

- name: Deploy clusters
  command: "kubectl apply -f /tmp/{{ cluster }}.yaml"
  register: createout
  changed_when: "'configured' in createout.stdout or 'created' in createout.stdout"
