spec:
  tlsSecret: operator-tls
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  subject:
    organizations:
      - NVIDIA Corporation
    organizationalUnits:
      - NGC Storage
    countries:
      - US
  dnsNames:
    - "localhost" 
    - "aistorecpu1004.nsv.sjc11.nvmetal.net"
    - "aistorecpu1005.nsv.sjc11.nvmetal.net"
    - "aistorecpu1006.nsv.sjc11.nvmetal.net"
  ipAddresses:
    - 127.0.0.1
    - 10.52.160.21
    - 10.52.160.20
    - 10.52.160.87
  emailAddress: ais@exchange.nvidia.com
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer