spec:
  tlsSecret: operator-tls
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  subject:
    organizations:
      - NVIDIA Corporation
    organizationalUnits:
      - NGC Storage
    countries:
      - US
  dnsNames:
    - "localhost" 
    - "aistorecpu1010.nsv.sjc4.nvmetal.net"
    - "aistorecpu1011.nsv.sjc4.nvmetal.net"
    - "aistorecpu1012.nsv.sjc4.nvmetal.net"
  ipAddresses:
    - 127.0.0.1
    - 10.150.56.227
    - 10.150.56.230
    - 10.150.56.225
  emailAddress: aistore@nvidia.com
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer