---
- name: Base64 encode JWT signing key
  set_fact:
    jwt_signing_key_base64: "{{ jwt_signing_key | b64encode }}"

- name: Create JWT Signing Key Secret file from template
  template:
    src: jwt-signing-key-secret.yaml.j2
    dest: /tmp/jwt-signing-key-secret.yaml

- name: Apply JWT Signing Key Secret configuration
  command: kubectl apply -f /tmp/jwt-signing-key-secret.yaml

- name: Create AuthN Default Config Map
  template:
    src: authn-default-config.yaml.j2
    dest: /tmp/authn-default-config.yaml

- name: Apply AuthN Default Config Map
  command: kubectl apply -f /tmp/authn-default-config.yaml

- name: Create AuthN PV/PVC for Config Dir
  template:
    src: authn-conf-dir-pv-pvc.yaml.j2
    dest: /tmp/authn-conf-dir-pv-pvc.yaml

- name: Apply AuthN PV/PVC for Config Dir
  command: kubectl apply -f /tmp/authn-conf-dir-pv-pvc.yaml

- name: Create AuthN Deployment file from template
  template:
    src: authn-deployment.yaml.j2
    dest: /tmp/authn-deployment.yaml

- name: Apply AuthN Deployment configuration
  command: kubectl apply -f /tmp/authn-deployment.yaml

- name: Patch AIS Operator to update environment variables for AuthN
  command: >
    kubectl patch deployment ais-operator-controller-manager
    -n {{ operator_namespace }}
    --type=json
    --patch '[{
      "op": "replace",
      "path": "/spec/template/spec/containers/0/env",
      "value": [
        {"name": "AIS_AUTHN_SU_NAME", "value": "{{ admin_username }}"},
        {"name": "AIS_AUTHN_SU_PASS", "value": "{{ admin_password }}"},
        {"name": "AIS_AUTHN_SERVICE_HOST", "value": "{{ authn_host }}"},
        {"name": "AIS_AUTHN_SERVICE_PORT", "value": "{{ authn_port | string }}"},
        {"name": "AIS_AUTHN_USE_HTTPS", "value": "{{ enable_https | lower | string }}"}
      ]
    }]'

- name: Create AuthN NodePort Service file from template
  template:
    src: authn-nodeport-service.yaml.j2
    dest: /tmp/authn-nodeport-service.yaml

- name: Apply AuthN NodePort Service configuration
  command: kubectl apply -f /tmp/authn-nodeport-service.yaml

- name: Create AuthN ClusterIP Service file from template
  template:
    src: authn-clusterip-service.yaml.j2
    dest: /tmp/authn-clusterip-service.yaml

- name: Apply AuthN ClusterIP Service configuration
  command: kubectl apply -f /tmp/authn-clusterip-service.yaml
