apiVersion: operators.coreos.com/v1beta1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: ais-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: AIStore is the Schema for the aistores API
      displayName: AIStore
      kind: AIStore
      name: aistores.ais.nvidia.com
      version: v1beta1
  description: AIStore operator
  displayName: aistore
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - AI
  - K8s
  links:
  - name: Ais Operator
    url: https://ais-operator.domain
  maturity: alpha
  provider:
    name: Nvidia
  version: 0.0.0
