- name: Operator version
  debug:
    msg: Deploying AIS Operator {{ operator_version }}

- name: Copy operator deploy script
  become: true
  template:
    src: "deploy-operator.sh.j2"
    dest: "/tmp/deploy-operator.sh"
    mode: "0755"

- name: Run deploy operator scripts
  shell: "/tmp/deploy-operator.sh"

- name: Wait for operator to be in Running state
  shell: "kubectl wait --for=condition=available deployment/ais-operator-controller-manager -n ais-operator-system --timeout=5m"
