# The "nobarrier" mount option is useful for kernels older than 4.13,
# but deprecated after that.
- name: set mount options (kernel < 4.13)
  set_fact:
    ais_fs_mount_options: noatime,nodiratime,logbufs=8,logbsize=256k,largeio,inode64,swalloc,allocsize=131072k,nobarrier
  when: ansible_kernel is version('4.12', '<=')

- name: set mount options (kernel >= 4.13)
  set_fact:
    ais_fs_mount_options: noatime,nodiratime,logbufs=8,logbsize=256k,largeio,inode64,swalloc,allocsize=131072k
  when: ansible_kernel is version('4.13', '>=')

- name: umount
  mount:
    src: "/dev/{{ item }}"
    path: "/ais/{{ item }}"
    state: unmounted
    fstype: xfs
    opts: "{{ ais_fs_mount_options }}"
  with_items:
    - "{{ ais_devices }}"
  when:
    - ais_fs_umount is defined
    - ais_fs_umount

- name: umount and remove from fstab
  mount:
    src: "/dev/{{ item }}"
    path: "/ais/{{ item }}"
    state: absent
    fstype: xfs
    opts: "{{ ais_fs_mount_options }}"
  with_items:
    - "{{ ais_devices }}"
  when:
    - ais_fs_umount_purge is defined
    - ais_fs_umount_purge

- name: mkfs
  filesystem:
    dev: "/dev/{{ item }}"
    force: yes
    fstype: xfs
    opts:
  with_items:
    - "{{ ais_devices }}"
  when:
    - ais_fs_losedata is defined
    - ais_fs_losedata == 'danger_danger'

- name: mount and populate fstab
  mount:
    src: "/dev/{{ item }}"
    path: "/ais/{{ item }}"
    state: mounted
    fstype: xfs
    opts: "{{ ais_fs_mount_options }}"
  with_items:
    - "{{ ais_devices }}"
  when:
    - ais_fs_mount is defined
    - ais_fs_mount

- name: chown and chmod ais dir
  file:
    path: "/ais/{{ item }}"
    state: directory
    mode: 0750
    owner: root
  with_items:
    - "{{ ais_devices }}"
  when:
    - ais_fs_mount is defined
    - ais_fs_mount
