apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsUser: 65532
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        image: controller:latest
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
          - name: operator-tls
            mountPath: /etc/operator/tls
            readOnly: true
        env:
        # Env variables for the AuthN (if its running in the same k8s cluster)
        - name: AIS_AUTHN_SU_NAME
          value: "admin" # Replace with the actual AuthN server admin username
        - name: AIS_AUTHN_SU_PASS
          value: "admin" # Replace with the actual AuthN server admin password
        - name: AIS_AUTHN_SERVICE_HOST
          value: "ais-authn.ais" # Replace with the actual AIS AuthN service host
        - name: AIS_AUTHN_SERVICE_PORT
          value: "52001" # Replace with the actual AIS AuthN service port
        - name: AIS_AUTHN_USE_HTTPS
          value: "true" # Set to "true" if AuthN is running with HTTPS
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 20Mi
      volumes:
        - name: operator-tls
          secret:
            secretName: operator-tls
            optional: true
      terminationGracePeriodSeconds: 10
