apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: OPERATOR_SKIP_VERIFY_CRT
          value: "True"
        # Env for AuthN (if it's running in the same k8s cluster)
        - name: AIS_AUTHN_SU_NAME
          value: "admin" # Replace with the actual AuthN server admin username
        - name: AIS_AUTHN_SU_PASS
          value: "admin" # Replace with the actual AuthN server admin password
        - name: AIS_AUTHN_SERVICE_HOST
          value: "ais-authn.ais" # Replace with the actual AIS AuthN service host
        - name: AIS_AUTHN_SERVICE_PORT
          value: "52001" # Replace with the actual AIS AuthN service port
        - name: AIS_AUTHN_USE_HTTPS
          value: "true" # Set to "true" if AuthN is running with HTTPS