---
- name: Add line for MQ variable in grub cfg
  lineinfile:
    path: /etc/default/grub
    regexp: '^MQ='
    line: 'MQ="scsi_mod.use_blk_mq=1 dm_mod.use_blk_mq=n"'
    insertbefore: '^GRUB_CMDLINE_LINUX='
    firstmatch: yes
    backup: yes
  register: addmq1

- name: Include MQ in GRUB_CMDLINE_LINUX
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX="\$GRUB'
    line: 'GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX $MQ"'
    insertafter: '^GRUB_CMDLINE_LINUX='
    backup: yes
  register: addmq2

- name: Update grub.cfg
  command: update-grub
  when: addmq1.changed or addmq2.changed

- name: Note reboot required
  debug:
    msg: Manual reboot is required for MQ change to take effect
  when: addmq1.changed or addmq2.changed