repositories:
  - name: aistore
    url: https://nvidia.github.io/ais-k8s/charts/

releases:    
  - name: ais-operator
    namespace: ais-operator-system
    createNamespace: true
    chart: aistore/ais-operator
    version: 2.3.0
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "bash"
        args:
          - "./check_cert_manager.sh"