environments: 
  default:
    values:
    - envFile: default
    - createCert:
        enabled: false
  authn:
    values:
    - envFile: authn
    - authn:
        enabled: true
    - createCert:
        enabled: false
  sjc11:
    values: 
    - envFile: authn
    - authn:
        enabled: true
    - createCert:
        enabled: true
    kubeContext: sjc11

---
repositories:
  - name: aistore
    url: https://nvidia.github.io/ais-k8s/charts/
---
releases:    
  - name: operator-tls-cert
    namespace: ais-operator-system
    createNamespace: true
    chart: tls-cert
    condition: createCert.enabled
    version: 0.1.0
    values:
      - "./config/tls-cert/{{ .Environment.Name }}.yaml"

  - name: operator-authn-cm
    namespace: ais-operator-system
    createNamespace: true
    chart: authn-cm
    condition: authn.enabled
    version: 0.1.0
    values:
      - "./config/authn-cm/{{ .Environment.Name }}.yaml"

  - name: ais-operator
    namespace: ais-operator-system
    createNamespace: true
    chart: aistore/ais-operator
    version: 2.5.0
    values:
      - "./config/operator/{{ .Values.envFile }}.yaml.gotmpl"
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "bash"
        args:
          - "./check_cert_manager.sh"