repositories:
  - name: ais-operator
    url: https://github.com/NVIDIA/ais-k8s/releases/download/v1.4.0/
    
---

releases:
  - name: ais-operator
    namespace: ais-operator-system
    createNamespace: true
    chart: ais-operator/ais-operator
    version: 0.1.0
    wait: true