environments:
  default:
    values:
      - certManager:
          enabled: true

---

repositories:
  - name: aistore
    url: https://nvidia.github.io/ais-k8s/charts/
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.16.1
    condition: certManager.enabled
    wait: true
    set:
      - name: crds.enabled
        value: true
    
  - name: ais-operator
    namespace: ais-operator-system
    createNamespace: true
    chart: aistore/ais-operator
    version: 2.0.1
    wait: true
    needs:
      - cert-manager/cert-manager
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "bash"
        args:
          - "./check_cert_manager.sh"