environments:
  default:
    values:
      - certManager:
          enabled: false

---

repositories:
  - name: ais-operator
    url: https://github.com/NVIDIA/ais-k8s/releases/download/v1.4.1/
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.16.1
    condition: certManager.enabled
    wait: true
    set:
      - name: installCRDs
        value: true
    
  - name: ais-operator
    namespace: ais-operator-system
    createNamespace: true
    chart: ais-operator/ais-operator
    version: 0.1.0
    wait: true
    needs:
      - cert-manager/cert-manager
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "bash"
        args:
          - "./check_cert_manager.sh"