---
- name: Copy cleanup mpath scripts
  copy:
    src: "clean-mpaths.sh"
    dest: "/tmp/"
    mode: 0777

- name: Run cleanup scripts
  shell: "MPATHS={{ mpaths | join(' ') | quote }} /tmp/clean-mpaths.sh"

- name: Run cleanup meta directory
  file:
    state: absent
    path: "/etc/ais/{{ cluster }}"
