---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.caCertificate.name }}
  namespace: cert-manager
spec:
  isCA: true
  commonName: selfsigned-ca
  secretName: {{ .Values.ca_cert_secret }}
  duration: {{ .Values.caCertificate.duration }}
  renewBefore: {{ .Values.caCertificate.renewBefore }}
  privateKey:
    algorithm: {{ .Values.caCertificate.privateKey.algorithm }}
    encoding: {{ .Values.caCertificate.privateKey.encoding }}
    size: {{ .Values.caCertificate.privateKey.size }}
  subject:
    organizations: {{ .Values.caCertificate.subject.organizations }}
    organizationalUnits: {{ .Values.caCertificate.subject.organizationalUnits }}
    countries: {{ .Values.caCertificate.subject.countries }}
  issuerRef:
    name: {{ .Values.clusterIssuer.name }}
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.Issuer.name }}
spec:
  ca:
    secretName: {{ .Values.ca_cert_secret }}