environments: 
  default:
    values:
    - https:
        enabled: false
  sjc11:
    values: 
    - https:
        enabled: true
---

repositories:
  - name: ais-operator
    url: https://github.com/NVIDIA/ais-k8s/releases/download/v1.2.0/
    
---

releases:
  - name: ais-operator
    namespace: ais-operator-system
    createNamespace: true
    chart: ais-operator/ais-operator
    version: 0.1.0
    wait: true

  # Defines a self-signed issuer for acquiring a tls cert
  - name: ais-tls-issuer
    namespace: ais
    createNamespace: true
    chart: charts/tls-issuer
    version: 0.1.0
    condition: https.enabled
    values:
      - "./config/tls-issuer/{{ .Environment.Name }}.yaml"

  # Acquires a tls cert from the specified issuer and stores in a secret for AIS
  - name: ais-tls-cert
    namespace: ais
    createNamespace: true
    chart: charts/tls-cert
    version: 0.1.0
    condition: https.enabled
    needs:
      - ais-tls-issuer
    values:
      - "./config/tls-cert/{{ .Environment.Name }}.yaml"
      - "./config/ais/{{ .Environment.Name }}.yaml"
    
  - name: ais-cluster
    namespace: ais
    createNamespace: true
    chart: charts/ais-cluster
    version: 0.1.0
    # Without this, helm diff cannot validate the CRD because the operator has not yet created it
    disableValidationOnInstall: true
    needs:
      - ais-operator-system/ais-operator
    values:
      - "./config/ais/{{ .Environment.Name }}.yaml"
    # Install pre-req local-path-provisioner to the cluster
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.27/deploy/local-path-storage.yaml"