- name: Delete all AIS configuration files from all nodes
  shell: find {{ host_path_prefix }} -type f -name ".ais*" -exec rm {} +
  ignore_errors: true
  when: host_path_prefix is defined and host_path_prefix != ""
