---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: aistore-podmonitor
  namespace: monitoring
  labels:
    podMonitorSelector: prometheus
spec:
  podMetricsEndpoints:
    - path: /metrics
      port: http
      interval: 30s
      # Uncomment for HTTPS AIS cluster
      # scheme: https
      # tlsConfig:
      #   insecureSkipVerify: true
  namespaceSelector:
    matchNames:
      - ais
  selector:
    matchLabels:
      app: ais
