---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    podMonitorSelector: prometheus
  name: aistore-podmonitor
  namespace: monitoring
spec:
  podMetricsEndpoints:
  - interval: 30s
    port: http
    path: /metrics
    # Used for https AIS cluster
    # scheme: https
    # tlsConfig:
    #   insecureSkipVerify: true
  namespaceSelector:
    matchNames:
    - ais
  selector:
    matchLabels:
      app: "ais"
