---
# This playbook destroys a specified cluster. Use with caution.

- name: Destroy cluster from controller
  hosts: "controller"
  vars_prompt:
  - name: "destroy_confirmation"
    prompt: "Are you sure you would like to destroy cluster {{ cluster }}? Type 'yes' to confirm."
    default: "no"
    private: no
  
  - name: "delete_conf"
    prompt: "Would you also like to delete all .ais.conf and .ais.override_config files from all nodes"
    default: "no"
    private: no

  pre_tasks:
    - name: check confirmation
      fail:
        msg: "destroy cluster not confirmed/forced"
      when: destroy_confirmation != "yes"

    - name: check cluster name
      fail:
        msg: "cluster name not specified!"
      when: cluster is undefined

  gather_facts: false
  become: true
  roles:
    - role: ais_destroy_cluster

- name: Reset AIS configuration
  hosts: "{{ cluster }}"
  gather_facts: no
  become: true
  roles:
    - role: ais_reset_config