# pretask - check if cluster is defined, controller is defined, ais_devices, ais_mpaths, ais_mpath_size
- name: "Check if all variables exist"
  hosts: 'localhost'
  gather_facts: false
  vars_files:
    - "host-config/vars/ais_datafs.yml"

  pre_tasks:    
    - name: Validate if ais_hosts is defined
      fail:
        msg: "Variable 'ais_hosts' not found. Add the 'ais_hosts' variable during execution. Use: ansible-playbook -i hosts.ini ais_host_config.yml -e ais_hosts=ais"
      when: ais_hosts is undefined

# Setting up host-config
- hosts: 'localhost'
  tasks:
    - debug:
        msg: "AIStore advises using XFS formatted drives, mounted at /ais/<device>. The following play sets up necessary filesystems for AIStore. Details: https://github.com/NVIDIA/ais-k8s/blob/main/playbooks/host-config/docs/ais_datafs.md"

- name: Display disk information and check filesystem type
  hosts: "{{ ais_hosts }}"
  gather_facts: false
  vars_files:
    - "host-config/vars/ais_datafs.yml"

  vars_prompt:
    - name: disk_info_confirmation
      prompt: "Check disk mounts and XFS formatting on all hosts?"
      default: "no"
      private: no

  roles:
    - role: host-config/roles/check_disk_info
      when: disk_info_confirmation | bool

# Run host-config/ais_datafs_mkfs.yml
- import_playbook: host-config/ais_datafs_mkfs.yml

- hosts: 'localhost'
  tasks:
    - debug:
        msg: "The upcoming playbook, `host-config/ais_host_config_common.yml`, tunes the system for AIStore by maximizing open file descriptor limits in /etc/security/limits.conf and applying key sysctls from host-config/vars/host_config_sysctl.yml. For details, visit: https://github.com/NVIDIA/ais-k8s/blob/main/playbooks/host-config/docs/ais_host_config_common.md"

# Run host-config/ais_host_config_common.yml
- import_playbook: host-config/ais_host_config_common.yml

# TODO: add post kube-spray playbook
