#
# Config specific to GPU hosts
#
---
- hosts: '{{ playhosts | default("gpu-worker-node") }}'
  vars_files:
    - "vars/host_config_packages.yml"

  gather_facts: true
  roles:
    - { role: ais_gpuhost_config }
    - { role: ais_gpuhost_device_plugin }



