---
# Playbook for switching the deployment protocol for AIS (HTTP ⇌ HTTPS)

- name: Manage AIS configuration and deployment
  hosts: "{{ cluster }}"
  gather_facts: false
  become: true
  vars_files:
    - "vars/ais_mpaths.yml"
  tasks:
    - name: Check for mountpath list
      fail:
        msg: "No AIS mountpaths specified!"
      when: ais_mpaths is undefined

    - name: Check for mountpath size
      fail:
        msg: "No AIS mountpath size specified!"
      when: ais_mpath_size is undefined

    - name: Delete .ais.smap files from all nodes
      shell: find /etc/ais/ -type f -name ".ais.smap" | xargs rm
      ignore_errors: true

    - name: Delete .ais.conf files from all nodes
      shell: find /etc/ais/ -type f -name ".ais.conf" | xargs rm
      ignore_errors: true
      when: delete_conf | default(false) | bool

    - name: Delete .ais.override_config files from all nodes
      shell: find /etc/ais/ -type f -name ".ais.override_config" | xargs rm
      ignore_errors: true
      when: delete_conf | default(false) | bool

- name: Delete all AIS pods from the cluster
  hosts: controller
  gather_facts: false
  roles:
    - ais_delete_all_pods

- name: Deploy AIS cluster again
  hosts: controller
  gather_facts: false
  roles:
    - ais_switch_protocol
  vars_files:
    - "vars/ais_mpaths.yml"
