---
- hosts: "controller"
  gather_facts: false
  vars_files:
    - "vars/multihome.yml"
  pre_tasks:
    - name: Check cluster variable
      fail:
        msg: "No cluster specified!"
      when: cluster is undefined
    - name: Check network_attachment variable
      fail:
        msg: "`network_attachment` name must be provided!"
      when: network_attachment is undefined or network_attachment | length == 0
  roles:
    - create_network_definition
