---
# Service for the AuthN Server to be accessed by CLI, SDKs, etc.
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nodeport
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.applicationPort }}
      nodePort: {{ .Values.nodePort }}
  type: NodePort
---
# Service for the AuthN Server to be accessed by AIS-Operator
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.applicationPort }}
---
{{- if .Values.lb.enabled }}
# Service for external access to AuthN
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-lb
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with .Values.lb.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.lb.port }}
      targetPort: {{ .Values.applicationPort }}
  type: LoadBalancer
  {{- if .Values.lb.clusterIP }}
  clusterIP: {{ .Values.lb.clusterIP }}
  {{- end }}
{{- end }}