version: "2"
run:
  concurrency: 0
  go: 1.24.1
  tests: true # Enable linting test files.
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - canonicalheader
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - fatcontext
    - gochecksumtype
    - gocritic
    - goheader
    - gomoddirectives
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - intrange
    - misspell
    - nolintlint
    - prealloc
    - protogetter
    - reassign
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: math/rand$
              desc: '`math/rand` package has been deprecated use `math/rand/v2`'
    errcheck:
      check-type-assertions: false
      check-blank: true
    gocritic:
      disabled-checks:
        - ifElseChain
        - unnamedResult
      enabled-tags:
        - performance
        - style
    gosec:
      excludes:
        - G115 ## dependency: https://github.com/kubernetes/apimachinery/blob/master/pkg/util/intstr/intstr.go#L32-L36
        - G401
        - G402
        - G404
        - G501
    govet:
      disable:
        - fieldalignment # TODO: Enable, for now reports a lot of problems.
        - shadow # Reports a lot of false-positives and conflicts with other linters.
      enable-all: true
    misspell:
      locale: US
    prealloc:
      simple: true # Report preallocation suggestions only on simple loops that have no returns/breaks/continues/gotos in them
      range-loops: true # Report preallocation suggestions on range loops, true by default
      for-loops: true # Report preallocation suggestions on for loops, false by default
    revive:
      severity: warning
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: early-return
        - name: error-naming
        - name: error-strings
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: indent-error-flow
        - name: modifies-value-receiver
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: string-of-int
        - name: superfluous-else
        - name: time-naming
        - name: var-naming
        - name: var-declaration
        - name: unconditional-recursion
        - name: unexported-naming
        - name: unexported-return
        - name: unnecessary-stmt
        - name: unreachable-code
        - name: unused-parameter
        - name: unused-receiver
        - name: waitgroup-by-value
    staticcheck:
      dot-import-whitelist:
        - "github.com/onsi/gomega"
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        text: Error return value of # ignores 'error return value of ... is unchecked'
      - linters:
          - revive
        text: or a comment on this block
      - linters:
          - unused
        text: '`noCopy` is unused'
      - linters:
          - gocritic
        text: 'importShadow: shadow of imported'
      - linters:
          - gocritic
        text: 'builtinShadow: shadowing of predeclared identifier: new'
      - linters:
          - gocritic
        source: /// # commentFormatting
      - linters:
          - gocritic
        source: //== # commentFormatting
      - linters:
          - staticcheck
        text: 'SA5011:' # produces a lot of false-positives; hopefully in the future we could enable it!
      - linters:
          - gocritic
        text: block doesn't have definitions # Sometimes blocks are useful for better readability.
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
