kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "0.0.0.0"
# Add to apiServer certSANs the name of the docker (dind) service in order to be able to reach the cluster through it.
# Note that in the future version of the `ClusterConfiguration` might change, so we have to also update it.
kubeadmConfigPatchesJSON6902:
  - group: kubeadm.k8s.io
    version: v1beta3
    kind: ClusterConfiguration
    patch: |
      - op: add
        path: /apiServer/certSANs/-
        value: docker
nodes:
  - role: control-plane
  - role: worker
  - role: worker
