cluster: ais
mpathInfo:
  storageClass: "ais-local-storage"
  size: 13.2Ti
  paths:
    - /ais/vdc
    - /ais/vdd
    - /ais/vde
    - /ais/vdf
    - /ais/vdg
    - /ais/vdh
    - /ais/vdi
size: 12
protocol: https
https:
  skipVerifyCert: false
  tlsSecret: "tls-certs"
imagePullSecrets:
  - name: regcred
nodeImage:
  tag: v4.0-fuse
initImage:
  tag: v4.0
logSidecarImage:
  tag: v1.1
cloud:
  awsSecretName: "aws-creds"
configToUpdate:
  memsys:
    min_free: 8GiB
    to_gc: 8GiB
    hk_time: 3m
  backend:
    aws: {}
  net:
    http:
      idle_conn_time: 20s
      idle_conns: 2048
      idle_conns_per_host: 128
stateStorageClass: "local-path"
authNSecretName: "ais-authn-jwt-signing-key"
proxyLB:
  enabled: true