global:
  nodes: 
    - 10.49.41.16
    - 10.49.41.61
    - 10.49.41.56
  namespace: ais
  cluster: ais
  mpathSize: 6.2Ti
  mpaths:
    - /ais/nvme0n1
    - /ais/nvme1n1
    - /ais/nvme2n1
    - /ais/nvme3n1
    - /ais/nvme4n1
    - /ais/nvme5n1
    - /ais/nvme6n1
    - /ais/nvme7n1
    - /ais/nvme8n1
    - /ais/nvme9n1
    - /ais/nvme10n1
    - /ais/nvme11n1
  storageClass: "ais-local-storage"
size: 3
protocol: http
nodeImage:
  name: aistorage/aisnode
  tag: v3.26-312a648
initImage:
  name: aistorage/ais-init
  tag: v3.26-a7ac713
logSidecarImage:
  name: aistorage/ais-logs
  tag: v1.0
cloud:
  awsSecretName: "aws-creds"
  gcpSecretName: ""
multihome:
  enabled: false
  hostnameMap: 
  networkAttachment:
shutdownCluster: false
cleanupData: false
cleanupMetadata: false
stateStorageClass: "local-path"
authNSecretName:
logsDir:
proxySpec:
  resources:
    requests:
      cpu: "8"
    limits:
      cpu: "32"
targetSpec:
  resources:
    requests:
      cpu: "128"
    limits:
      cpu: "192"
  hostNetwork: false