cluster: ais
mpathInfo:
  storageClass: "ais-local-storage"
  size: 6.2Ti
  paths:
    - /ais/nvme0n1
    - /ais/nvme1n1
    - /ais/nvme2n1
    - /ais/nvme3n1
    - /ais/nvme4n1
    - /ais/nvme5n1
    - /ais/nvme6n1
    - /ais/nvme7n1
    - /ais/nvme8n1
    - /ais/nvme9n1
    - /ais/nvme10n1
    - /ais/nvme11n1
size: 3
nodeImage:
  tag: v3.26-312a648
initImage:
  tag: v3.26-a7ac713
logSidecarImage:
  tag: v1.1
cloud:
  awsSecretName: "aws-creds"
stateStorageClass: "local-path"
proxySpec:
  resources:
    requests:
      cpu: "8"
    limits:
      cpu: "32"
targetSpec:
  resources:
    requests:
      cpu: "128"
    limits:
      cpu: "192"