global:
  nodes: 
    - 10.49.41.3
    - 10.49.41.39
    - 10.49.41.32
    - 10.49.41.110
    - 10.49.41.40
    - 10.49.41.72
    - 10.49.41.66
    - 10.49.41.17
    - 10.49.41.25
    - 10.49.41.23
    - 10.49.41.99
    - 10.49.41.55
    - 10.49.41.27
    - 10.49.41.89
    - 10.49.41.4
    - 10.49.41.67
  namespace: ais
  cluster: ais
  mpathSize: 6.2Ti
  mpaths:
    - /ais/nvme0n1
    - /ais/nvme1n1
    - /ais/nvme2n1
    - /ais/nvme3n1
    - /ais/nvme4n1
    - /ais/nvme5n1
    - /ais/nvme6n1
    - /ais/nvme7n1
    - /ais/nvme8n1
    - /ais/nvme9n1
    - /ais/nvme10n1
    - /ais/nvme11n1
  storageClass: "ais-local-storage"
size: 16
protocol: http
imagePullSecrets:
  - name: regcred
nodeImage:
  name: aistorage/aisnode
  tag: v3.30
initImage:
  name: aistorage/ais-init
  tag: v3.30
logSidecarImage:
  name: aistorage/ais-logs
  tag: v1.1
cloud:
  awsSecretName: "aws-creds"
  gcpSecretName: ""
configToUpdate:
  memsys:
    min_free: 8GiB
    to_gc: 8GiB
    hk_time: 3m
  net:
    http:
      idle_conn_time: 20s
      idle_conns: 2048
      idle_conns_per_host: 128
multihome:
  enabled: false
  hostnameMap: 
  networkAttachment:
shutdownCluster: false
cleanupData: false
cleanupMetadata: false
stateStorageClass: "local-path"
authNSecretName:
logsDir:
proxySpec:
  # TODO: change these to 51082 and 51083. Kept this for now as cluster is already deployed.
  portIntraControl: 51081
  portIntraData: 51082
  resources:
    requests:
      cpu: "8"
    limits:
      cpu: "32"
targetSpec:
  resources:
    requests:
      cpu: "128"
    limits:
      cpu: "192"
  hostNetwork: false