global:
  nodes: 
    - 10.49.41.3
    - 10.49.41.39
    - 10.49.41.32
    - 10.49.41.110
    - 10.49.41.40
    - 10.49.41.72
    - 10.49.41.66
    - 10.49.41.17
    - 10.49.41.25
    - 10.49.41.23
    - 10.49.41.99
    - 10.49.41.55
    - 10.49.41.27
    - 10.49.41.89
    - 10.49.41.4
    - 10.49.41.47
  job_namespace: ais-jobs
  namespace: ais
  cluster: ais
  mpath_size: 6.2Ti
  mpaths:
    - /ais/nvme0n1
    - /ais/nvme1n1
    - /ais/nvme2n1
    - /ais/nvme3n1
    - /ais/nvme4n1
    - /ais/nvme5n1
    - /ais/nvme6n1
    - /ais/nvme7n1
    - /ais/nvme8n1
    - /ais/nvme9n1
    - /ais/nvme10n1
    - /ais/nvme11n1
size: 16
protocol: http
nodeImage:
  name: aistorage/aisnode
  tag: v3.26-a7ac713
initImage:
  name: aistorage/ais-init
  tag: v3.26-a7ac713
cloud:
  awsSecretName: "aws-creds"
  gcpSecretName: ""
multihome:
  enabled: false
  hostnameMap: 
  networkAttachment:
hostNetwork: false
shutdownCluster: false
cleanupData: false
cleanupMetadata: false
stateStorageClass: "local-path"
authNSecretName:
logsDir:
proxySpec:
  resources:
    requests:
      cpu: "8"
    limits:
      cpu: "32"
targetSpec:
  resources:
    requests:
      cpu: "128"
    limits:
      cpu: "192"