global:
  nodes: 
    - aistorecpu1004.nsv.sjc11.nvmetal.net
    - aistorecpu1005.nsv.sjc11.nvmetal.net
    - aistorecpu1006.nsv.sjc11.nvmetal.net
  namespace: ais
  cluster: ais
  mpathSize: 5.8Ti
  mpaths:
    - /ais/nvme0n1
    - /ais/nvme1n1
    - /ais/nvme2n1
    - /ais/nvme3n1
    - /ais/nvme4n1
    - /ais/nvme5n1
    - /ais/nvme6n1
    - /ais/nvme7n1
    - /ais/nvme8n1
    - /ais/nvme9n1
    - /ais/nvme10n1
    - /ais/nvme11n1
    - /ais/nvme12n1
    - /ais/nvme13n1
    - /ais/nvme14n1
    - /ais/nvme15n1
  storageClass: "ais-local-storage"
size: 3
protocol: https
https:
  skipVerifyCert: false
  tlsSecret: "tls-certs"
nodeImage:
  name: aistorage/aisnode
  tag: v3.29
initImage:
  name: aistorage/ais-init
  tag: v3.29
logSidecarImage:
  name: aistorage/ais-logs
  tag: v1.1
configToUpdate:
  memsys: 
    hk_time: 3m
  backend:
    aws: {}
multihome:
  enabled: false
  hostnameMap: 
  networkAttachment:
shutdownCluster: false
cleanupData: false
cleanupMetadata: false
stateStorageClass: "local-path"
apiMode:
authNSecretName:
logsDir:
proxySpec:
  tolerations:
    - key: "node.kubernetes.io/disk-pressure"
      operator: "Exists"
      effect: "NoExecute"
targetSpec:
  annotations:
    nvault.nvidia.com/agent-auto-config: 'true'
    nvault.nvidia.com/agent-inject: 'true'
    nvault.nvidia.com/vault-agent-http-reload-enable: 'true'
    nvault.nvidia.com/auth-jwt-mount-path: 'jwt/nvidia/sjc11/aawilson-dev'
    nvault.nvidia.com/auth-jwt-role: 'ais'
    nvault.nvidia.com/namespace: 'ngc-storage-aistore'
    nvault.nvidia.com/vault-addr: 'https://stg.vault.nvidia.com'
    nvault.nvidia.com/vault-agent-template-cnt-aws-config-secrets: |
      {{- with secret "nvidia/cluster/sjc11/cloud/aws/kv/config" }}
      {{ .Data.data.config }}
      {{- end }}
    nvault.nvidia.com/vault-agent-template-cnt-aws-cred-secrets: |
      {{- with secret "nvidia/cluster/sjc11/cloud/aws/kv/credentials" }}
      {{ .Data.data.credentials }}
      {{- end }}
    nvault.nvidia.com/vault-agent-template-dst-aws-config-secrets: aws/config
    nvault.nvidia.com/vault-agent-template-dst-aws-cred-secrets: aws/credentials
  tolerations:
    - key: "node.kubernetes.io/disk-pressure"
      operator: "Exists"
      effect: "NoExecute"
  env:
    - name: AWS_CONFIG_FILE
      value: "/vault/secrets/aws/config"
    - name: AWS_SHARED_CREDENTIALS_FILE
      value: "/vault/secrets/aws/credentials"
  resources:
    requests:
      cpu: "24"
    limits:
      cpu: "32"
  hostNetwork: false