cluster: ais
mpathInfo:
  storageClass: "ais-local-storage"
  size: 9.1Ti
  paths:
    - "/ais/sda"
    - "/ais/sdb"
    - "/ais/sdc"
    - "/ais/sdd"
    - "/ais/sde"
    - "/ais/sdf"
    - "/ais/sdg"
    - "/ais/sdh"
    - "/ais/sdi"
    - "/ais/sdj"
size: 3
protocol: http
nodeImage:
  tag: latest
initImage:
  tag: latest
logSidecarImage:
  tag: v1.1
configToUpdate:
  memsys: 
    hk_time: 3m
  backend:
    aws: {}
  net:
    http:
      idle_conn_time: 20s
      idle_conns: 2048
      idle_conns_per_host: 128
stateStorageClass: "local-path"