# Global section contains values used by both AIS and AIS `create-pv` sub-chart
global:
  nodes: 
    - aistorecpu1004.nsv.sjc11.nvmetal.net
    - aistorecpu1005.nsv.sjc11.nvmetal.net
    - aistorecpu1006.nsv.sjc11.nvmetal.net
  job_namespace: ais-jobs
  namespace: ais
  cluster: ais
  mpath_size: 5.8Ti
  mpaths:
    - /ais/nvme0n1
    - /ais/nvme1n1
    - /ais/nvme3n1
size: 3
protocol: http
https:
  skipVerifyCert: true
  tlsSecret: "tls-certs"
nodeImage:
  name: aistorage/aisnode
  tag: v3.26-a7ac713
initImage:
  name: aistorage/ais-init
  tag: v3.26-a7ac713
# Optional
logSidecarImage:
  name: aistorage/ais-logs
  tag: v1.0
cloud:
  awsSecretName: "aws-creds"
  gcpSecretName: "gcp-creds"
multihome:
  enabled: false
  hostnameMap: 
  networkAttachment:
hostNetwork: false
shutdownCluster: false
# Set one and only one of the below options for config and state storage. See docs/state_storage.md
# DEPRECATED: hostpathPrefix defines a location on the physical k8s node. Use stateStorageClass
hostpathPrefix: "/etc/ais"
# stateStorageClass defines an existing storage class for dynamic creation of k8s volumes
stateStorageClass: "local-path"
cleanupData: false
cleanupMetadata: false
authNSecretName:
logsDir:
proxySpec:
  # If provided, overrides cluster size
  size: 3
  resources:
targetSpec:
  # currently REQUIRED to be provided IF cloud.gcpSecretName is set above
  env: 
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: "/var/gcp/gcp.json"
  size: 3
  resources: